hw1
AlexLyash/2019-2-Atom-Frontend-A-Lyashenko pull request #1
Opened 2019-10-04 19:12 UTC by AlexLyash

# Домашнее задание № 1

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
Files* were edited with respect to the tasks.
*convertBytesToHuman.js, correctSentence.js, nonUniqueElements.js, and convertBytesToHuman.test.js

2019-10-04 21:12 UTC, chexex requested changes
Связать репозиторий с travis-ci.org

2019-10-04 21:12 UTC, chexex commented on atom-mail/.travis.yml
> +  - npm run build
```
script:
  - npm run test
  - npm run build
```

2019-10-04 21:12 UTC, chexex commented on atom-mail/.travis.yml
> +  - cd web-components
для первого дз эти строчки не нужны. их нужно пока что удалить

2019-10-04 21:12 UTC, chexex commented on atom-mail/.travis.yml
> +  local_dir: web-components/build
```suggestion
  local_dir: build
```

2019-10-04 21:12 UTC, chexex commented on atom-mail/package.json
> +  "homepage": "https://track-mail-ru.github.io/atom-mail/",
```suggestion
  "homepage": "https://AlexLyash.github.io/2019-2-Atom-Frontend-A-Lyashenko/",
```

2019-10-06 06:55 UTC, AlexLyash commented
Алексей, спасибо за ревью
Travis я привязал.
Код, если это не критично, поправлю во вторник днём, когда доберусь до своего ноута. Я его оставляю в институте

2019-10-06 12:03 UTC, chexex commented
Теперь, когда трэвис привязан, нужно что-нибудь закоммитить в репозиторий, чтобы заставить трэвис собирать

2019-10-06 13:14 UTC, AlexLyash commented
Я когда привязывал к тревису закинул в мастер .travis.yml, где написано:
language: node_js

2019-10-08 12:10 UTC, AlexLyash commented on atom-mail/.travis.yml
> +      - hw1
Я добавил в список веток в которых тревис запускает проект текущую: 'hw1'.
Однако, проект не собрался. Судя по ошибке npm не нашёл файлы с тестами, хотя это не точно

2019-10-09 18:18 UTC, chexex commented
Нужно вынести все содержимое папки `atom-mail` наружу (в корень проекта), тогда все заработает :)

2019-10-18 13:16 UTC, martinkomitsky commented
@AlexLyash скоро будет фикс?

2019-10-18 13:52 UTC, AlexLyash commented
@martinkomitsky Я решил, что можно так оставить. Сегодня перекину папки

2019-10-20 11:45 UTC, martinkomitsky commented
@AlexLyash желательно, конечно, задания от преподавателей выполнять :) у тебя даже сборка сломалась из-за того, что ты решил.

2019-10-20 20:07 UTC, AlexLyash commented
Так, теперь проект начал собираться. Но почему-то не до конца.
Ошибка:
../binding.cc:4:22: fatal error: node_api.h: No such file or directory

2019-10-20 21:14 UTC, AlexLyash commented
Ура, теперь всё взлетело. Нужно было ещё с токеном разобраться

2019-10-21 08:22 UTC, chexex commented
удлить из репозитория (`git rm -r node_modules coverage`)
```
node_modules
coverage
```

Добавить их в .gitignore

2019-10-22 18:10 UTC, chexex approved these changes
10 баллов

2019-10-22 18:10 UTC, merged